### ISSUE TITLE
Can we use the non-dev react?

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#117]
Right now we're using the dev-mode react bundles.

https://github.com/mytakedotorg/mytakedotorg/blob/54f57a3e6cb8c05894f7285dc6edf93665c7497b/server/src/main/resources/assets.conf#L5-L6

Ideally, we'd use the right bundle for the right usecase (`runDev` vs heroku).

**Comment by WebsByTodd** [comment]
Yes.

They only benefit to dev-mode React is error messages and warnings. To date on this project, I think these notices have been useful exactly once. I can easily switch back to dev-mode bundles if I need them.

**Comment by WebsByTodd** [comment]
cafd220b917d14fb55192842b51c72280791cf85

Will be merged with next PR.
