### ISSUE TITLE
Homepage / newsfeed MVP

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#12]
Here's a mockup of our homepage: https://nedtwigg.github.io/mytake/

For styling purposes, we can build this without any serverside functionality.  Most of the interesting stuff - clustering and newsfeed curation - can't happen until we have a body of work anyway.

**Comment by WebsByTodd** [comment]
This is just about as far as it's going to get for the MVP, the only thing missing is a sample article with a video in the preview. @nedtwigg are you interested in creating one of these?

**Comment by nedtwigg** [comment]
I'll definitely make at least one, feel free to add your own if you have any ideas.

**Comment by nedtwigg** [comment]
We're going to use a manually-curated homefeed for now.  What we've got looks decent!
