### ISSUE TITLE
Server MVP

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#14]
We can prove a lot about our idea without serverside functionality.  But in order to launch a full product, we're going to need:

- login via Facebook & Twitter
- saving drafts and publishing
- ratings/likes of some kind
- follow an author

Anything else an MVP would need?  I'm going to create a separate issue for building discussion.

**Comment by WebsByTodd** [comment]
I was messing around with the HashRouter of React Router on my own time and created a little demo of full client side routing:

https://github.com/nedtwigg/mytake/tree/feature/react-router

pros:

- No HTML files/structure needed, it all loads from within the root index.html.
- No server needed. Anything React can do on a single page, can be taken across multiple pages.
- No page loading between routes, client has already downloaded the bundle.js file and is running it.
- Easy to pass data between "routes". Routes can be treated as a stack of views, each with their own state that can be maintained, even when the browser back/forward buttons are pressed.

cons:

- Ugly URLs.
- No SEO for pages handled by React Router.
- No server rendering is ever possible on hash routes.

For a great description of using React Router for multi-page React apps, see https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writting-manually?rq=1

**Comment by nedtwigg** [comment]
> No HTML files/structure needed, it all loads from within the root index.html.

Why is this a pro?  I don't think it's a con either, just seems neutral.

> No server needed. Anything React can do on a single page, can be taken across multiple pages.

We'll still need a server to serve that index.html.  It's no harder to run a server with 5 index.html's than 1.

Also, what will store user accounts?  Saved and published articles?  I think we'll still need a server.

> Ugly URLs.

I was hoping we could do GitHub-style `mytake.org/toddriley/some_specific_take`.  That makes it easier for people to link to each other's work.

> No SEO.

This is huge!

> No server rendering.

This is minor for now, but could definitely become important.  We'd like to be popular with low-income folks, which means we'd like to be easy-to-read on the worst phones out there.

**Comment by WebsByTodd** [comment]
When I think about separating the views of the reading and writing experiences and creating a feed of takes I see a lot of stuff that can be done outside of React or inside React. I also see multiple pages. When I search "multi page react app", React Router is the most popular answer. This is a quick attempt of implementing React Router with what we have and the pros and cons of the completely serverless approach. There are many other approaches to explore.

**Comment by nedtwigg** [comment]
> When I search "multi page react app", React Router is the most popular answer.

"React" is in the search terms.  The easiest way to build a multipage website is certainly not to use react.

IMO, we're building a pretty standard website, and we're using React to implement some of the pages.

There have been a few big-name co's that built SPA's and then dumped them for plain-old webpages because they were faster to load and easier to maintain.  GitHub and Twitter are the ones that I can remember off-hand, but I can't find GitHub's blog post about it.

https://adamsilver.io/articles/the-disadvantages-of-single-page-applications/

Definitely explore away, but I'm super-skeptical that our page structure is complicated enough to warrant an SPA.  `<a href` FTW!

**Comment by nedtwigg** [comment]
We've got one.  :D
