### ISSUE TITLE
Fontawesome and SRI

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#141]
Our font awesome script:

```
<script src="https://use.fontawesome.com/be03d6dcba.js"></script>
```

Does not allow SRI.  I can't figure out where the link came from.  Are there alternatives we could use, @WebsByTodd?

**Comment by WebsByTodd** [comment]
The Font Awesome 4 CDN used custom embed codes which are sent via email per user. (http://fontawesome.io/get-started)

Font Awesome 5 was recently released and we should probably upgrade. Steps for the upgrading are at https://fontawesome.com/how-to-use/upgrading-from-4

After upgrading, the new script will be:

```
<script defer src="https://use.fontawesome.com/releases/v5.0.3/js/all.js"></script>
```
