### ISSUE TITLE
meta.mytake navigation

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#159]
See https://meta.mytake.org/t/header-on-mytake-org-vs-meta-mytake-org/40/3

**Comment by nedtwigg** [comment]
Possible ideas:

Header for main page:  "Always in context.  Always true."
Header for meta: "Forum for MyTake.org"

**Comment by nedtwigg** [comment]
Also the about page has the wrong budget link (the old one).  Correct link is: https://docs.google.com/spreadsheets/d/1SZtK9ajcQAs8la1dqnHtc9yAWJK7j-26HBrAx-gtUDY/edit#gid=2094784737

**Comment by nedtwigg** [comment]
I think our new design (logo and header) will last for a little while, so I think it's worth updating our header to match.

**Comment by WebsByTodd** [comment]
Updated.

**Comment by nedtwigg** [comment]
On desktop, if I press any of the buttons in the top-right of discourse, it's hitting the GitHub banner instead.  Works great on mobile though.  Looks great on both 👍
 
<img width="327" alt="screen shot 2018-03-18 at 9 12 09 pm" src="https://user-images.githubusercontent.com/2924992/37577745-3ff5e0b6-2af1-11e8-84e3-e009de28693c.png">

**Comment by WebsByTodd** [comment]
Tough one, unless we increase the header height another 50px. The image does not look good if it's smaller. For now I just don't display it until the browser width is at least 1410px, which is wide enough that the image clears the discourse icons.
