### ISSUE TITLE
Gradle/Rocker issue

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#166]
When I make a change to a rocker.html file I kill my gradle and gulp tasks and restart them, but the changes don't take effect. I have to run/kill/restart `./gradlew runDev` once more in order for the changes to take effect.

**Comment by WebsByTodd** [comment]
This is hit or miss. Sometimes it works and sometimes it doesn't. I've been having a lot of little dev environment issues lately, so I'm gonna chalk it up to that.

**Comment by nedtwigg** [comment]
Another option is to call `gradlew cleanCompileRocker`.  I encountered problems with rocker up-to-dateness in the past.  If you can find a reproducible testcase, there's an old issue for it: https://github.com/etiennestuder/gradle-rocker-plugin/issues/5
