### ISSUE TITLE
Favicon.ico

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#169]
We need to smush our logo into a favicon.  This does a good job with our raw logo: http://www.favicomatic.com/

But we'll have to manually swap-out the wheat for the tree at smaller sizes.

**Comment by nedtwigg** [comment]
Btw, I realized I have a license to a program called IcoFX which handles this well.  I'll take this one, might ask @WebsByTodd for some exported vectors.

**Comment by nedtwigg** [comment]
Implemented in #172

**Comment by nedtwigg** [comment]
Works on Firefox and Safari.  Edge displays the tree.  Chrome displays nothing.  Will debug later...

**Comment by WebsByTodd** [comment]
I see it on Chrome. Windows/Chrome might need some help clearing the cache to see it:

https://stackoverflow.com/questions/2208933/how-do-i-force-a-favicon-refresh#answer-32823504

**Comment by nedtwigg** [comment]
Awesome!  Working for me now too.
