### ISSUE TITLE
Error dialog asks to copy paste, but it is impossible to do so

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#170]
Here's what a clientside error looks like in Chrome:

![image](https://user-images.githubusercontent.com/2924992/37433863-d434eb64-279a-11e8-80a0-4357dd40bc60.png)

Unfortunately, it's impossible to copy-paste the text from this popup...

**Comment by WebsByTodd** [comment]
The popup you see looks different than the popup I see.  What I see can be copied/pasted. What happens if you press Ctrl-C after the alert appears?

http://code2care.org/2015/how-to-copy-chrome-alert-popup-text-to-clipboard/

**Comment by nedtwigg** [comment]
Looks like it's a (possibly windows-specific) chrome bug:
https://productforums.google.com/forum/#!topic/chrome/sM6TTZDZNh0

I reported as well.  Guess no action necessary from us :)

**Comment by WebsByTodd** [comment]
We could change our message to say "Press Ctrl-C to copy this message" for now.

**Comment by nedtwigg** [comment]
Even that doesn't work on Windows Chrome right now.
