### ISSUE TITLE
Add prerequisites to README

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#185]
I had to start docker on my machine to get the server to come up. Also I'm not sure if other local things are required, like a Java installation for example, or if this can all be wrapped up in the docker container.

**Comment by nedtwigg** [comment]
It would be cool to have a layman's "Don't trust us?  You can run MyTake.org on your own laptop.  See for yourself that the search results we give you are *exactly* the same as the results your own laptop gives you.  There's nowhere for bias to hide on MyTake.org."
