### ISSUE TITLE
Issue in Bush/Dukakis 2

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#190]
I started running into issues towards the end of the last change in the diff of 8b768492a where the transcript says

> Michael S Dukakis: That's the way you bring a deficit down and help to improve the quality of life for people at the same time.

the transcript GUI begin highlighting very large chunks of text instead of just a word or 2 at a time.

**Comment by nedtwigg** [comment]
I think there's two problems.  One is that the .said transcript isn't very accurate:

https://github.com/mytakedotorg/mytakedotorg/pull/189/commits/b0dff72bdfe497f39523e66f98af573ead2a02b9

Maybe this is better? https://www.nytimes.com/1988/10/14/us/the-presidential-debate-transcript-of-the-second-debate-between-bush-and-dukakis.html

I think the second problem is that there's a loop in the video from here: https://youtu.be/nwSJkn69PS4?t=1h2m33s

To here: https://youtu.be/nwSJkn69PS4?t=1h6m30s

Right before the break, he says: `modest amount of medical care for the elderly`
After the break, he says: `to cut Social Security, to cut Medicare,`

This whole section is duplicated:

> to cut Social Security, to cut Medicare, to cut these basic entitlements to people of very, very modest means.

> Now, there are some things we can do to help people who currently do get entitlements to get off of public assistance. I talked at our first debate about the possibilities of helping millions and millions of welfare families to get off of welfare. And I'm proud to say that we finally have a welfare reform bill. And the Ruby Samsons and Don Lawsons, hundreds of thousands of welfare mothers in this country and in my state and across the country who today are working and earning, are examples of what can happen when you provide training for those welfare mothers, some day care for their children so that those mothers can go into a training program --

> MODERATOR: Governor.

> DUKAKIS: -- and get a decent job. That's the way you bring a deficit down and help to improve the quality of life for people at the same time.

> MODERATOR: One minute for the Vice President.

> BUSH: I think I've addressed it, but let me simply say for the record I did not vote to cut COLA's. And I voted the same way that he did three months before in a national governors' conference. And he said at that time, quote, and this is a paraphrase, a freeze, that's easy. So I don't believe that we need to do what you've suggested here. And I've said that I'm going to keep this Social Security entitlement, to keep that trust fund sound. But I do think there are flexible ways to solve some of the pressing problems, particularly that affect our children. And I have made some good sound proposals. But, again, we've got a big difference on child care, for example. You see, I want the families to have the choice. I want - I don't want to see the Federal Government licensing grandmothers. I don't want to see the, the Federal Government saying to communities, ''Well you can't do this anymore; we're going to tell you how to do it all.'' I want flexibility. And I do - you know, these people laugh about the thousand points of life. You ought to go out and - light - you ought to go out and see, around this country, what's happening in the volunteer sector. Americans helping America. And I want to keep it alive in --

> MODERATOR: Mr. Vice President --

> BUSH: -- child care and in other entitlements.

> MODERATOR: Margaret Warner for Governor Dukakis. Stand on Social Security

> Q. Governor, I'm going to pass on the question I originally planned to ask you to follow up on your rebuttal to a question Andrea asked. And that involved Social Security. Now it is true, as you said, that originally you sought an exemption for Social Security COLA's in this National Governors' Association vote. --

> DUKAKIS: Right.

> Q. -- But when you lost that vote, you then endorsed the overall freeze proposal and, what's more, you had great criticism of your fellow governors who wouldn't go along, as political cowards. You said --

> DUKAKIS: That is absolutely not true --

> Q. -- You said it takes guts --

> DUKAKIS: No. That is absolutely --

> Q. -- and it takes will.

> DUKAKIS: It is absolutely not true. It had nothing to do with the debate on Social Security. It had to do with the discussion we had had the previous day on the overall question of reducing the budget --

> Q. My question is, aren't you demagoguing the Social Security issue?

> DUKAKIS: No. And, and I have to - I have to - I just have to correct the record. That simply isn't true. Now, we're not a parliamentary body, the National Governors' Association. We vote on resolutions. If you don't get a two-thirds, then your resolution doesn't pass. But everybody knew that those of us who voted against the freezing of COLA's did so - we did so emphatically. And I never made that statement. Never would. The point is that as we look at this nation's future, and we have two very different visions of this future. I want to move ahead. The Vice President talks about a thousand points of light. I'm interested in 240 million points of light. I'm interested in 240 million citizens in this country who, who share in the American dream. All of them, in every part of this country.

> But as we look at the decisions that the next President of the United States is going to have to make, I just don't believe the place you go first is those programs, those so-called entitlements which provide a basic floor of income and a modest amount of medical care for the elderly

Has the quality of the video been pretty good otherwise?  I can snip this extra part out, or we can find a new source entirely.

**Comment by WebsByTodd** [comment]
The quality of the video was fine up until this point. Even the transcript seemed ok. If it's easier to snip it out I think that will work. Thanks for tracking this down.

**Comment by nedtwigg** [comment]
- broken in [1988-10-13 - Presidential Debate - Bush, Dukakis (2 of 2) - Internal loop](https://youtu.be/nwSJkn69PS4) (unlisted)
- fixed in [1988-10-13](https://youtu.be/KxvfacuEbnA)
