### ISSUE TITLE
Issue in Kennedy/Nixon 4

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#192]
The video will not play in the transcript gui. The error is:

> This video contains content from SME. It is restricted from playback on certain sites or applications

I believe this is a Sony copyright issue. The first second or two of the video has a little sound byte that could be the culprit. The first 11 seconds of the video are from an offscreen announcer and aren't a part of the debate. If the video is trimmed, maybe the violation will go away.

**Comment by nedtwigg** [comment]
I uploaded a new version without any intro music, and got a violation just the same!  Turns out it's from an [audio documentary about the debate](https://www.youtube.com/watch?v=KaXLU6SzcUg).

I have filed a dispute with YouTube on these grounds:

> The content we uploaded is the original, unedited fourth debate of the 1960 presidential election.  We obtained this content from C-SPAN, which licenses this content for non-commercial use even if it weren't already in the public domain (we are a non-profit).  https://www.c-span.org/about/copyrightsAndLicensing/

> The SME title "1960 Debate on Cuba" is an audio documentary, and it uses snippets of this debate in its analysis.  Obviously they own their documentary, but they do not own the widely-published primary documents which it uses, such as this debate.

> A blunt analogy - a documentary about MLK should not make it impossible for others to publish or remix the "I have a dream speech".

**Comment by nedtwigg** [comment]
While the dispute is active, it worked in the transcriptGui, and I was able to sync.

**Comment by nedtwigg** [comment]
It appears that we won the dispute.
