### ISSUE TITLE
Hiccup in Carter/Ford 1

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#194]
Between 945 and 948 seconds there is no audio or video.

--Edit
Also there is a segment of text in the transcript that is cut from the video. At 3572 seconds Jimmy Carter says:

> That's got to be changed. A few things that can be done: we have now a deferral system so that the multinational corporations who invest overseas - if they make a million dollars in profits overseas - they don't have to pay any of their taxes unless they bring their money back into this country. When they don't pay their taxes, the average American pays the taxes for them. Not only that, but it robs this country of jobs, because instead of

Between "but from investments." and "coming back with that million dollars"

**Comment by nedtwigg** [comment]
The hiccup is fixed in #232, at the cost that I'll have to restart the sync.
