### ISSUE TITLE
Image generation for social embeds

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#204]
Just to retrace the history:

- We have javascript code that can generate an image that includes the highlighted part of the transcript / document.
- This is the only way to include that important content in social embeds.

We tried to use J2V8 to call into V8, but it didn't work.  The main problem was that we couldn't get the canvas library to link.  We tried multiple versions of J2V8, and multiple OSes, and made no progress.

Here is my proposal:

- we make a new folder `node`
- we will deploy this to `node.mytake.org`, where we can put any node-based API's we need
- this app will have no database, it will be a stateless function of its inputs
    + this allows cloudflare to do aggressive caching for the domain
- because there's no database, we don't get much value from the heroku platform
- we get a *lot* more CPU/$ at digitalocean than at heroku
- we will deploy like this:
    + ssh into `node.mytake.org`
    + kill node
    + git pull
    + start node
- Pros
    + it's easy
    + it gets us running
- Cons
    + two different deployment pipelines
    + our webapp testing infrastructure is in java, not node

**Comment by WebsByTodd** [comment]
This is up and running now.
