### ISSUE TITLE
Fix a few canvas API issues

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#214]
This is all most likely in the `DrawFacts.ts` file on the node server.

- [ ]  Bold Source Sans Pro font isn't working. Maybe there is an issue here with node-canvas and a multiple word font name? Just a guess.
- [ ] Highlighted text creates a line break afterwards. This should not happen. 

<img width="961" alt="screen shot 2018-09-29 at 2 51 11 pm" src="https://user-images.githubusercontent.com/15790480/46249454-89245c00-c3f7-11e8-8f56-cbd5c64e567c.png">

- [ ] Margins above text are not working in production, but they are working for me locally.

local:
<img width="353" alt="screen shot 2018-09-29 at 2 50 13 pm" src="https://user-images.githubusercontent.com/15790480/46249418-08fdf680-c3f7-11e8-9e00-c09275045e67.png">
production:
<img width="373" alt="screen shot 2018-09-29 at 2 50 26 pm" src="https://user-images.githubusercontent.com/15790480/46249419-0bf8e700-c3f7-11e8-892c-2cb5f39c366c.png">

**Comment by nedtwigg** [comment]
I think we're going to move to puppeteer, so this is moot.
