### ISSUE TITLE
Video clips in search results don't play correctly

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#222]
As of `prod/2018-04-15`, if you go to https://mytake.org/search?q=trump you'll get results from "Obama, Romney (1 of 3)" and "Carter, Reagan (1 of 1)".  For me on a mac with Chrome, the Carter/Reagan clip always works, and the Obama/Romney clips work 1 out of 4  times.  It's pretty random when it works and when it doesn't.

**Comment by WebsByTodd** [comment]
Minimally reproducible code sample below. Issue appears to be either with communicating through the YouTube API itself for this particular video, or with the `react-youtube` library. Further investigation is needed to determine if `react-youtube` is the cause of the problem.

In this example when the page loads we attempt to autoplay each video beginning at 100 seconds and ending at 104 seconds. The Carter/Reagan video always works flawlessly, yet the Obama/Romney video is inconsistent. Sometimes it will not autoplay at all. Other times it will autoplay from the beginning. And other times it will autoplay at the correct start time, yet have no sound.

It should be noted that the Obama/Romney video has a higher resolution (720p) than the Carter/Reagan video (360p). Not sure if this is relevant.

```
import React from "react";
import YouTube, { Options } from "react-youtube";

const OBAMA_ROMNEY_LINK = "e4nibedK7GM";
const CARTER_REAGAN_LINK = "a1J1TkWCLhs";

const opts: Options = {
  height: "315",
  width: "560",
  playerVars: {
    autoplay: 1,
    // cc_lang_pref: "en", // <-- missing from the @types/react-youtube typedefs file
    cc_load_policy: 1,
    controls: 1,
    end: 104,
    modestbranding: 1,
    playsinline: 1,
    rel: 0,
    showinfo: 0,
    start: 100
  }
};

function App() {
  return (
    <YouTube
      videoId={OBAMA_ROMNEY_LINK}
      opts={opts}
      className="video__video"
    />
  );
}

export default App;
```

**Comment by nedtwigg** [comment]
Another thought: `youtube-dl` makes it easy to download a video.  Once downloaded, you can run `ffprobe` on that file, and it will tell you a lot about the video encoder settings.  There are a *bazillion* encoding options.  Whenever you upload to YouTube, it seems that YouTube re-encodes anyway.  But I wonder if how YouTube encodes depends at all on what you upload.

**Comment by nedtwigg** [comment]
An even better hint.  If I search ["border security" ](https://mytake.org/search?q=border%20security), I get one result, and it never works when I click "play".  But if I click "open", [the player there](https://mytake.org/foundation-v1/presidential-debate-bush-kerry-3-of-3/3111.110-3115.830) always works.

**Comment by WebsByTodd** [comment]
The border security example works fine in the minimally reproducible code. Hmm 🤔

**Comment by nedtwigg** [comment]
Are you able to reproduce the "search" part?  Clicking "play" in the search just plays from the beginning, but if you click "Open", and then "Play Clip", that works?

**Comment by WebsByTodd** [comment]
Sorry, I should have clarified that. I see what you see. 

1. "Play" in the search plays from the beginning. 
2. "Open" followed by "Play Clip" works as expected. 
3. And the additional evidence is that the Bush/Kerry video works in the minimal repro code.

**Comment by nedtwigg** [comment]
I think it's likely that we have two separate issues, which cause overlapping symptoms:

1) this most recent piece of evidence is close to a smoking gun that there's a search-specific bug on our side
2) your minimal reproducible example shows that there is fuzzy-to-reproduce bug in the player itself

Fixing (1) would be a big help and should be fairly tractable, compared to (2) which will likely require help from the `react-youtube` authors.

**Comment by nedtwigg** [comment]
Possibly useful evidence - the transcriptGui starts from the beginning almost all the time for most of the videos.  I'll be digging deeper into this during Piper's nap tomorrow (roughly 1pm-3pm PST), and then again after bedtime (7pm- PST to late).  I'll try to collect as many useful details as I can for you in the 1-3pm window.

**Comment by nedtwigg** [comment]
More hints!  For the new Carter/Ford debate, the transcriptGui always plays from the beginning when you click "play".  But, if you click "play" a second time, after it has started playing from the beginning, then it will play at the correct location.  It seems like we need to put the player into some kind of "loaded and paused" state, and the problem is that sometimes we're trying to take it straight from "uninitialized" to "play at this exact location", and instead it's just going from "uninitialized" to "play".

**Comment by nedtwigg** [comment]
I recorded the behavior with commentary in case that's helpful: https://drive.google.com/open?id=1lse1vPfsQ81AWgyFZf8BYJlDiukDlas8

**Comment by nedtwigg** [comment]
If you run `./gradlew transcriptGui`, it will build and start.  Click the `...` to the right (there's a pause), then select a video.

The top-right YoutubeCtl is running this:

https://github.com/mytakedotorg/mytakedotorg/blob/02fdf3c986fb77fc99ae0b8eb9fa6a29bd0642d8/foundation-gen/src/test/java/org/mytake/foundation/transcript/gui/YoutubeCtl.java#L55-L127

If you add a `System.out.println()`, it will get built the next time you run `transcriptGui`.  Likewise, if you change the code, it will be running that changed code.

**Comment by nedtwigg** [comment]
Here it is printed out:

```html
<html><body>
<div id="player">...loading</div>
<script type="text/javascript">
	var tag = document.createElement('script');
tag.src = "https://www.youtube.com/iframe_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
var player;
function onYouTubeIframeAPIReady() {
	player = new YT.Player('player', {
		height: '390',
		width: '640',
		videoId: 'HZ_r26R-cUo',
		events: {
			'onReady': onPlayerReady,
			'onStateChange': onPlayerStateChange
		}
	});
}
var playerIsReady = false;
function onPlayerReady(event) {
	playerIsReady = true;
}
function onPlayerStateChange(event) { 
	if (event.data === 0) {
		// Video ended
		stopTimer();
		secondsElapsed = 0;
	} else if (event.data === 1) {
		// Video playing
		startTimer();
	} else if (event.data === 2) {
		// Video paused
		stopTimer();
	} else if (event.data === 3) {
		// Video buffering
		stopTimer();
	}
}
var duration = 0;
var play = function(start, end) {
	if (playerIsReady) {
		duration = end - start;
		if (duration < 1) {
			duration = 1;
		}
		player.seekTo(start);
		startTimer();
	} else {
		alert("player not ready, try again");
	}
}
var timerId;
var secondsElapsed = -1;
function startTimer() {
	secondsElapsed += 1;
	if (secondsElapsed >= duration) {
		stopTimer();
		player.stopVideo();
	} else { 
		timerId = window.setTimeout(startTimer, 1000);
	}
};
function stopTimer() {
	secondsElapsed = -1;
	if (timerId) {
		window.clearTimeout(timerId);
		timerId = null;
	}
};
</script>
</html></body>
```

The gui calls the `play(start, end)` function, which you could also call from browser console.  gtg.

**Comment by WebsByTodd** [comment]
All the videos are greyed out, indicating (I guess) that they are completed.

**Comment by WebsByTodd** [comment]
Ok, I've got a fix. I'm not sure of the best way to update YoutubeCtl.java since it has string escaped the html, but here's the updated code. PR coming for the react portion, but unable to get my local build to work so gonna defer to a heroku build for testing.

```
<html><body>
  <div id="player">...loading</div>
  <script type="text/javascript">
    var tag = document.createElement('script');
  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '390',
      width: '640',
      videoId: 'HZ_r26R-cUo',
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }
  var playerIsReady = false;
  var expectedStartTime;
  function onPlayerReady(event) {
    playerIsReady = true;
  }
  function onPlayerStateChange(event) { 
    if (event.data === 0) {
      // Video ended
      stopTimer();
      secondsElapsed = 0;
    } else if (event.data === 1) {
      // Video playing
      console.log("playing");
      if (player.getCurrentTime() < expectedStartTime) {
        // seek again
        console.log("seeking again");
        player.seekTo(expectedStartTime);
      }
      startTimer();
    } else if (event.data === 2) {
      // Video paused
      stopTimer();
    } else if (event.data === 3) {
      // Video buffering
      stopTimer();
    }
  }
  var duration = 0;
  var play = function(start, end) {
    expectedStartTime = start;
    if (playerIsReady) {
      duration = end - start;
      if (duration < 1) {
        duration = 1;
      }
      player.seekTo(start);
      startTimer();
    } else {
      alert("player not ready, try again");
    }
  }
  var timerId;
  var secondsElapsed = -1;
  function startTimer() {
    secondsElapsed += 1;
    if (secondsElapsed >= duration) {
      stopTimer();
      player.stopVideo();
    } else { 
      timerId = window.setTimeout(startTimer, 1000);
    }
  };
  function stopTimer() {
    secondsElapsed = -1;
    if (timerId) {
      window.clearTimeout(timerId);
      timerId = null;
    }
  };
  </script>
  </html></body>
```

**Comment by nedtwigg** [comment]
All the problem examples in this issue are resolved by the small changes in https://github.com/mytakedotorg/mytakedotorg/pull/235.  Amazing, thanks!!
