### ISSUE TITLE
www.mytake.org goes to Heroku landing page

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#230]
www.mytake.org  sends to a Heroku landing page

**Comment by WebsByTodd** [comment]
It would appear as if you've fixed this.

**Comment by nedtwigg** [comment]
Still broken for me.

**Comment by WebsByTodd** [comment]
Oh weird. It's working on my laptop but not my phone.

**Comment by WebsByTodd** [comment]
Last night I checked incognito on my phone and it was working, switched back to regular and it wasn't. Now it's working everywhere for me.

**Comment by nedtwigg** [comment]
Fixed with:

<img width="811" alt="Screen Shot 2020-08-12 at 2 20 00 PM" src="https://user-images.githubusercontent.com/2924992/90069289-f74e3100-dca6-11ea-83c8-127335a046b0.png">
