### ISSUE TITLE
Timeline errors after dependency upgrade

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#234]
vis (our Timeline) doesn't appear to be playing nicely with react 16. There's a new dependency for react that could be worth exploring: https://www.npmjs.com/package/react-visjs-timeline.

**Comment by WebsByTodd** [comment]
Oh fun, I did some googling and I found myself. vis doesn't work with react 16 so we never upgraded. I'll try the new react-visjs-timeline to see if that gets around it.

https://github.com/mytakedotorg/mytakedotorg/commit/024615c972b40ee2e41ec3266f731a34d20ff39a

**Comment by nedtwigg** [comment]
I think the driver for the react 16 upgrade was to fix the video sync, so not sure if this is a priority.  I'm all for keeping deps up-to-date, so fine with me if this stays open, or fine with me if you close.  I'll let you make the call.  Seems like you did a fair amount of work to do the react upgrade, might be a bummer to lose that while it's still fresh enough to put back in easily.

**Comment by WebsByTodd** [comment]
I'll leave it open, I think I can get it merged in by April. If I can't then it can be closed.

**Comment by WebsByTodd** [comment]
#242 address this. I couldn't get `react-visjs-timeline` to work.

**Comment by nedtwigg** [comment]
Please reopen if I misunderstand, but #242 bumps to react 16 and the timeline works great, so I think this is resolved.
