### ISSUE TITLE
Remove `console.error` debug logging

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#253]
We added some `console.error` debug logging in #247 which needs to be removed but I'm gonna merge it anyway to fix our formatting issues now.

**Comment by WebsByTodd** [comment]
We actually have `console.error` messages in another part of the node app as well. These shouldn't negatively impact a production deployment in any way so I think this is not so important to remove these. I'm going to close this issue until we have a better error logging solution in place, but feel free to reopen if you disagree.

**Comment by nedtwigg** [comment]
Sounds good to me.
