### ISSUE TITLE
Bug visible in https://mytake.org/search?q=the%20press

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#271]
I'm pretty sure the root cause is that the Lucene search server is finding results which the client's regex does not agree with, so it's really an instance of #181.

However, if the client doesn't see any results, it should remove it from the list, rather than sit on it.

**Comment by WebsByTodd** [comment]
After some investigation, I don't think this is an instance of #186. The server returns 1 result for Kennedy/Nixon 1.

```
{
hash: "WSNNQEyeRYnfycmvCTlpJUrLYwG9P1KLWC2r22qdBJ8="
turn: 42
}
```

But the term "the press" does not actually appear at all in this debate (according to a ctrl-f inside `foundation/src/main/resources/foundation-data/WSNNQEyeRYnfycmvCTlpJUrLYwG9P1KLWC2r22qdBJ8=.json`).

I still agree that the client shouldn't render a result if it can't find a match.

**Comment by nedtwigg** [comment]
I edited my original comment and your reply, it should be #181.  Turn 42 has this snippet `in his kickoff press conference`.  So the server is including that for "the press", but the client is not.  The bug is in the server side, but the root cause is a difference between the two.

**Comment by WebsByTodd** [comment]
Fixed the client-side by only rendering matches it can find #280
