### ISSUE TITLE
Client-side hot reloading bug

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#276]
Update and save a TS file while the client proxy is running. The screenshot below appears in the dev console and the page does not reload. A manual reload will get the update properly.

![Screen Shot 2020-07-27 at 10 51 05 AM](https://user-images.githubusercontent.com/15790480/88556673-47669b80-cff7-11ea-8db3-a46282364cdb.png)

**Comment by WebsByTodd** [comment]
Check out https://github.com/facebook/react/issues/16604#issuecomment-528663101

**Comment by nedtwigg** [comment]
Over my head :)

**Comment by WebsByTodd** [comment]
Sure, I meant "check this out" as more of a note-to-self.
