### ISSUE TITLE
Explore TimelineView refactor

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#291]
The mechanism that syncs the URL and the React state in `TimelineView.tsx` can be extracted. See `urlValues` in `TimelineViewState` and the `parseUrl` method on the TimelineView class. If this extraction makes the components simpler then it should be implemented.

**Comment by nedtwigg** [comment]
Addressed in #324, especially 0f26bc1c4911466112f1dd28d992d5acd9e3f4cd
