### ISSUE TITLE
Question about search result counter

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#310]
I thought it'd be useful to know the total number of search results returned, so I added the count to the header on the search page. The count represents the number of items in our list of search results, not necessarily the number of times a particular word was said. E.g. for the "wall, -wall street" search, there are 7 search hits, even though "wall" was spoken 14 times.

The sentence: 

> It's a disaster. Hillary Clinton wanted the __wall__. Hillary Clinton fought for the __wall__ in 2006 or thereabouts. Now, she never gets anything done, so naturally the __wall__ wasn't built. But Hillary Clinton wanted the __wall__.

counts as a single search result. If you toggle the "sentences containing word" radio button, there will be 14 search results and the total will change in the header.

The n-gram includes the total number of times a word was found, regardless of a how frequently it's spoken. 14 in this example - 11 in 2016, 1 in 2008, and 2 in 1984.

Another approach is to show the total number of hits - "14 Search Results" - regardless of how the search hits are grouped. @nedtwigg which approach do you prefer?

**Comment by nedtwigg** [comment]
I think we should always show the "hit count", grouping shouldn't change the total.  So for the example sentence above, we should always show 4, not 1.
