### ISSUE TITLE
Confirm 1:1 mapping for `video.ts`: `cutToTurn` and `turnToCut`

### ISSUE THREAD

**Issue by nedtwigg** [mytakedotorg/mytakedotorg#337]
This should be an exact, lossless conversion back and forth.  There's a little jitter right now, we should fix that someday.

**Comment by WebsByTodd** [comment]
Search for `wall, -wall street` and bookmark the very last result, (Clinton/Trump 3/3 where Trump says "And the wall."). Navigate to the bookmarks page and notice the wrong turn is shown. This is a situation where the 2 speakers are talking over one another. Turn 45 is very short and the end of turn 44 is very close to the beginning of turn 46, so our binary search in `cutToTurn` function is returning a cut that overlaps turns. The cut is `[1330.128, 1330.75]` and `cutToTurn` returns 

```
{
  cut: [39, 57],
  text: "are- And the wall.",
  turn: 44
}
` ``

Turn 45 in its entirety is `And the wall`. This is the turn we want.
