### ISSUE TITLE
Broken Foundation footer link

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#393]
This doesn't work.

<img width="154" alt="Screen Shot 2020-09-28 at 8 17 17 AM" src="https://user-images.githubusercontent.com/15790480/94431368-2fc8a200-0163-11eb-81cf-b22bb96917ef.png">

**Comment by nedtwigg** [comment]
`feat/git-fact` has a fix, will hopefully get fixes later today.

**Comment by nedtwigg** [comment]
Fixed!
