### ISSUE TITLE
Handle Foundation sub-routes

### ISSUE THREAD

**Issue by WebsByTodd** [mytakedotorg/mytakedotorg#62]
The idea is for each Fact of the Foundation to be accessible via its own URL.

### `/foundation/`
- Renders a Timeline.
### `/foundation/bill-of-rights#/samples/does-a-law-mean-what-it-says-or-what-it-meant/&368&513&336`
- Renders the Bill of Rights Document with preexisting highlights and a Timeline.
### `/foundation/bill-of-rights`
- Should render the Bill of Rights Document without highlights, but currently throws an error.

Without a web server we need to manually create the filesystem structure for each foundation sub-route (e.g. `/foundation/amendment-13`, `/foundation/Jimmy-Carter-Gerald-Ford-1/`, etc.)

Our React entry point (`/src/index.tsx`) handles the `/foundation/bill-of-rights/` route but fails if the hash URL is empty. This should be updated to handle routes with no hash URLs. It should render the Fact above a Timeline.

**Comment by nedtwigg** [comment]
When you click a fact, it should update the URL bar.

**Comment by WebsByTodd** [comment]
This issue was created pre-server and it's a bit out of date. I don't think anything needs to change server-side for this. As you say, when a user clicks a Fact, the URL should update.

An example of a working URL:

`/foundation#bill-of-rights&/samples/does-a-law-mean-what-it-says-or-what-it-meant&283&439&283&439&171.5`

And one that doesn't work, but should work:

`/foundation#bill-of-rights`

**Comment by nedtwigg** [comment]
Out-of-date issue, implemented.
